[package]
name = "sjmb_slack"
version = "0.1.0"
edition = "2021"
resolver = "2"
authors = ["Sami J. Mäkinen <sjm@iki.fi>"]
description = "My Slack bot"
repository = "https://github.com/sjm42/sjmb-slack"
readme = "README.md"
keywords = ["slack", "bot"]
license = "MIT OR Apache-2.0"


[dependencies]
anyhow = "1.0"
chrono = "0.4"
chrono-tz = "0.8"
env_logger = "0.10"
futures = "0.3"
http = "0.2"
log = "0.4"
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = { version = "3.0", features = ["full"] }
slack-morphism = { version = "1.8", features = ["hyper", "axum"] }
sqlx = { version = "0.6", features = [
    "macros",
    "migrate",
    "runtime-tokio-native-tls",
    "sqlite",
    "offline",
] }
structopt = "0.3"
tokio = { version = "1.26", features = ["full"] }


[build-dependencies]
build-data = "0.1"


[profile.release]
lto = true
opt-level = "s" # static
# opt-level = 3 # default
# opt-level = 'z'  # Optimize for size.

# EOF
